-- OTS Hub — Telemetry table
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  instance_id text not null,
  balance numeric,
  equity numeric,
  status text,
  raw_data jsonb
);

alter table telemetry enable row level security;

create policy "Enable all for components"
on telemetry for all
using (true) with check (true);
